# This file was generated by the `rails generate rspec:install` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause this
# file to always be loaded, without a need to explicitly require it in any files.
#
# Given that it is always loaded, you are encouraged to keep this file as
# light-weight as possible. Requiring heavyweight dependencies from this file
# will add to the boot time of your test suite on EVERY test run, even for an
# individual file that may not need all of that loaded. Instead, make a
# separate helper file that requires this one and then use it only in the specs
# that actually need it.
#
# The `.rspec` file also contains a few flags that are not defaults but that
# users commonly want.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

require 'rspec/collection_matchers'

RSpec.configure do |config|

end

def sign_up(username)
  visit new_user_url
  fill_in 'username', :with => username
  fill_in 'password', :with => "biscuits"
  click_on "Create User"
end

def sign_in(username)
  visit new_session_url
  fill_in 'username', :with => username
  fill_in 'password', :with => "biscuits"
  click_on "Log In"
end

def create_goal(goal_name, private=false)
  visit new_goal_url
  fill_in 'goal', with: 'sample goal'
  check('private') if private
  click_button 'Create Goal'
end